#ifndef JHP_DEVTOOLS_RESIDS_HPP
#define JHP_DEVTOOLS_RESIDS_HPP


// !max value is type short max (32767)
#define JHP_DEVTOOLS_ABOUT_STRINGSID	32000
#define JHP_DEVTOOLS_MENU_STRINGSID		32500

#endif // JHP_DEVTOOLS_RESIDS_HPP

